import { motion } from "framer-motion";
import React, { useMemo } from "react";
import DecenIcon from "../public/assets/Icon/decen.svg";
import AboutIcon from "../public/assets/Icon/features-icon.svg";
import getScrollAnimation from "../utils/getScrollAnimation";
import ScrollAnimationWrapper from "./Layout/ScrollAnimationWrapper";

const abouts = [
  {
    icon: <DecenIcon />,
    button: "Decentralized:",
    content:
      "Decentralized AI node ecosystem that allows anyone to participate and earn $NET",
  },
  {
    icon: <DecenIcon />,
    button: "Revenue Sharing:",
    content:
      "Stake $GPU and earn a share of revenue generated by the NODE AI ecosystem",
  },
  {
    icon: <DecenIcon />,
    button: "Rent AI Nodes:",
    content:
      "Rent reality available AI servers for your own AI use cases and pay a monthly fee",
  },
  {
    icon: <DecenIcon />,
    button: "Lend GPU Power:",
    content:
      "Lend your inactive GPUs and earn $GPU based on the usage by the renter",
  },
];

const AboutFeature = () => {
  const scrollAnimation = useMemo(() => getScrollAnimation(), []);

  return (
    <div className="max-w-screen-lg py-20 px-5 mx-auto" id="aboutfeature">
      <div className="gap-8 flex flex-col justify-center items-center">
        <ScrollAnimationWrapper className="flex max-w-screen-sm w-full justify-end">
          <motion.div
            className="h-full flex flex-col items-center text-center w-full p-4 gap-6"
            variants={scrollAnimation}
          >
            <div className="text-[#BDFFE8] gap-2 flex text-[12px] font-medium bg-[#BDFFE826] border border-[#BDFFE8] rounded-full px-[14px] py-[7px]">
              Features <AboutIcon className="h-4 w-4 text-[#BDFFE8]" />
            </div>
            <h1 className="text-3xl lg:text-4xl xl:text-5xl font-medium text-[#BDFFE8] leading-normal">
              Our Features
            </h1>
            <p className="text-white-300 mt-4 mb-6">
              Nettensor is an AI Infrastructure service provider that emphasizes
              ease of access and other additional features such as Privacy
              Service and App Chain which are our best products in blockchain
              and decentralized industry.
            </p>
          </motion.div>
        </ScrollAnimationWrapper>
        <ScrollAnimationWrapper>
          <motion.div className="max-w-screen-lg flex justify-center w-full">
            <div className="grid sm:grid-cols-2 justify-between gap-[50px] w-full">
              {abouts.map((feature, index) => (
                <motion.div
                  className="rounded-[60px] col-span-1 p-[48px] border bg-[#00000070] border-[#5E45FF66] flex flex-col gap-6"
                  custom={{ duration: 2 + index }}
                  variants={scrollAnimation}
                  key={feature}
                  whileHover={{
                    scale: 1.01,
                    transition: {
                      duration: 0.1,
                    },
                  }}
                >
                  {feature.icon}
                  <div className="text-primary text-2xl">{feature.button}</div>
                  <div className="text-[#9DA5AF] font-normal">
                    {feature.content}
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </ScrollAnimationWrapper>
      </div>
    </div>
  );
};

export default AboutFeature;
