import { motion } from "framer-motion";
import React, { useMemo } from "react";
import DecenIcon from "../public/assets/Icon/decen.svg";
import AboutIcon from "../public/assets/Icon/features-icon.svg";
import getScrollAnimation from "../utils/getScrollAnimation";
import ScrollAnimationWrapper from "./Layout/ScrollAnimationWrapper";
import ButtonOutline from "./misc/ButtonOutline.";

const abouts = [
  {
    icon: <DecenIcon />,
    button: "Decentralized:",
    content:
      "Decentralized AI node ecosystem that allows anyone to participate and earn $NET",
  },
  {
    icon: <DecenIcon />,
    button: "Revenue Sharing:",
    content:
      "Stake $GPU and earn a share of revenue generated by the NODE AI ecosystem",
  },
  {
    icon: <DecenIcon />,
    button: "Rent AI Nodes:",
    content:
      "Rent reality available AI servers for your own AI use cases and pay a monthly fee",
  },
  {
    icon: <DecenIcon />,
    button: "Lend GPU Power:",
    content:
      "Lend your inactive GPUs and earn $GPU based on the usage by the renter",
  },
];

const ReadyStart = () => {
  const scrollAnimation = useMemo(() => getScrollAnimation(), []);

  return (
    <div
      className="max-w-screen-2xl rounded-[48px] bg-ready-start py-20 px-5 mx-auto"
      id="aboutfeature"
    >
      <div className="gap-8 flex lg:pt-[130px] flex-col justify-center items-center">
        <ScrollAnimationWrapper className="flex max-w-screen-sm w-full justify-end">
          <motion.div
            className="h-full flex flex-col items-center text-center w-full p-4 gap-4"
            variants={scrollAnimation}
          >
            <h1 className="text-3xl lg:text-4xl xl:text-5xl font-medium text-white-300 leading-normal">
              Ready To Start?
            </h1>
            <p className="text-white-300 mt-4 mb-6">
              Get ready to experience the full potential of AI and GPU with
              NetTAO. Seamlessly access computational power, earn rewards, and
              contribute to a decentralized ecosystem.
            </p>
            <ButtonOutline className={"border-2 bg-[#FFFFFF1A]"}>
              Launch dApp
            </ButtonOutline>
          </motion.div>
        </ScrollAnimationWrapper>
      </div>
    </div>
  );
};

export default ReadyStart;
